### PR TITLE
fix: make sure redis-node is fully sync before failover

### LINKED ISSUE #81: Cluster failover timeout
At the moment, when we have relatively large amount of data ( > 150 MB) on the nodes, we are getting timeout when running manual cluster failover:
```
1:S 13 Feb 2021 15:05:50.579 # Manual failover timed out.
```

### PR DESCRIPTION
**Pull request by shyimo**
- Logic change on master failover process: make sure promoted follower is fully sync and loaded before starting a manual failover
- add waitForRedisLoad function: make sure loading process is finished on a fresh node
- Verify follower node is fully sync before continue to the next one (in replicateLeader function)
- Enhance manual failover logs

close #81

### CODE REVIEW

File: controllers/rediscli/redis_info.go [hunk 1]
```diff
@@ -146,17 +147,35 @@ func (r *RedisClusterNode) IsFailing() bool {
...
+		if err != nil {
+			return "during sync, but unkown state"
+		}
+
+		if aofLastRewrite < 1 {
+			return "waiting for AOF rewrite child process to finish"
+		}
+
+		// master_sync_in_progress == 0 and Background AOF rewrite finished successfully
+		return ""
```
Comment (voltbit) [inline controllers/rediscli/redis_info.go:175]: The AOF logic should be kept separated as it is not related to sync but more to persistence. The GetSyncStatus method should only report about the sync status.

File: controllers/rediscli/redis_info.go [hunk 2]
```diff
@@ -146,17 +147,35 @@ func (r *RedisClusterNode) IsFailing() bool {
...
 	if r.Replication["role"] == "slave" {
 		if r.Replication["master_sync_in_progress"] != "0" {
 			p, found := r.Replication["master_sync_perc"]
 			if found {
-				return p
+				if found && len(p) > 0 {
+					return p
+				}
+
+				return "master_sync_in_progress"
```
Comment (voltbit) [inline controllers/rediscli/redis_info.go:161]: The inside if condition is redundant.
It is not clear why the 'master_sync_in_progress' string is returned.

**Review by voltbit — CHANGES_REQUESTED** [review]

**Review by voltbit — APPROVED** [review]
Looks good, good job :+1:
